### ISSUE TITLE
[Bug] dynamic class bind error

### ISSUE THREAD

**Issue by Mrzhangqc** [JuniorTour/vue-template-babel-compiler#13]
## Current behavior
``` js
<template>
  <div :class="{[`${componentCls}__single`]: true}">

    </div>
</template>
```
动态class绑定时控制台报错，
vue.esm.js:628 [Vue warn]: Error in render: "ReferenceError: _defineProperty is not defined"

## Expected behavior
期望正常解析

## Usage
vue2.0

**Comment by JuniorTour** [comment]
It is a bug.
We just publish `1.0.4` to fix this issue.

## You can try it by:
``` shell
npm install vue-template-babel-compiler@1.0.4 -D
// or yarn
yarn add vue-template-babel-compiler@1.0.4 -D
```

![83e1625d89cf2da9a41e8594942f4f7](https://user-images.githubusercontent.com/14243906/133261037-7e19e608-1b29-4962-98ad-eef2f367b386.png)


Thank you for your feedback!
