### ISSUE TITLE
[Bug] ?.使用不符合预期

### ISSUE THREAD

**Issue by lalahuang** [JuniorTour/vue-template-babel-compiler#24]
- [ ] Would you like to work on a fix?

## Current behavior
``` js
// your code goes here
```
![image](https://user-images.githubusercontent.com/17737354/143194874-4ad1caf6-dc9b-474b-89e5-2f74d33b2113.png)
![image](https://user-images.githubusercontent.com/17737354/143195017-23e437c6-51ad-47ae-b306-61039ee1fcbd.png)
applytime属性不存在的时候应该直接返回‘-’,而不是再读取substring方法

**Comment by JuniorTour** [comment]
谢谢你的反馈，但似乎你描述的表现是符合预期的，并非BUG，

我在浏览器的 console 里尝试执行了这两句：
``` js
({a: 1})?.b.substring ?? '_' // VM190:1 Uncaught TypeError: Cannot read properties of undefined (reading 'substring')

({a: 1})?.b?.substring ?? '_' // '_'
```

结果如下：
![image](https://user-images.githubusercontent.com/14243906/143202514-d58d1f16-7e72-4da5-8cfb-e6aa20722a45.png)

所以，截图中抛出错误是正确的行为。

如果你把截图中的代码改为 `item?.applyTime?.substring(0,10) ?? '_'`，即在`substring()`前使用一个可选链操作符 `?.`，应该就能按你的预期返回 `'_'` 了
