### ISSUE TITLE
[Bug] Get "ReferenceError: _toConsumableArray is not defined" when use ...

### ISSUE THREAD

**Issue by xachary** [JuniorTour/vue-template-babel-compiler#25]
## Current behavior
ReferenceError: _toConsumableArray is not defined.

## Expected behavior
No ReferenceError.

## Usage
```vue
{{ [...document.querySelectorAll('div')] }}
```

**Comment by JuniorTour** [comment]
It is a bug.

Currently Babel will transform `[...document.querySelectorAll('div')]` into:
``` js
function _toConsumableArray(arr) {
  // ...
}

_toConsumableArray(document.querySelectorAll("div"));
```

[Babel Playground DEMO Link](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=NoOjBMHsGMFcFsCmA7ALiAjrRAnAngMqIA2i0qkOAgscQBQDk4AlgG4MCUAukA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=true&targets=&version=7.16.4&externalPlugins=%40babel%2Fplugin-transform-spread%407.16.0&assumptions=%7B%7D)

<hr/>

May be we can fix it by add `"arrayLikeIsIterable": true` to `assumptions`, according to [babel-plugin-transform-spread Doc](https://babeljs.io/docs/en/babel-plugin-transform-spread#allowarraylike).

### Do you have interest to make a Pull Request to fix this issue?

### You can:
1. Try to reproduce this error. Setup [DEMO Project](https://github.com/JuniorTour/vue-template-babel-compiler-vue-cli-project) can help. 

2. Follow [CONTRIBUTING.md](https://github.com/JuniorTour/vue-template-babel-compiler/blob/main/CONTRIBUTING.md) to make a Pull Request.

**Comment by JuniorTour** [comment]
We just publish a beta version `1.0.7-beta.0` which will fix the error `_toConsumableArray is not defined.`

## You can install it by `yarn add vue-template-babel-compiler@beta` to try.

Thanks for your feedback again!

**Comment by JuniorTour** [comment]
> We just publish a beta version `1.0.7-beta.0` which will fix the error `_toConsumableArray is not defined.`
> 
> ## You can try it by `yarn add vue-template-babel-compiler@beta`.

`1.0.7-beta.0` did't fix this error, I will look into this deeply.

**Comment by JuniorTour** [comment]
We just publish `v1.1.2`, it will fix this issue,

Try it by:
``` shell
npm install vue-template-babel-compiler@latest
// or 
yarn add vue-template-babel-compiler@latest
```

Thanks for your feedback again!
