### ISSUE TITLE
[Bug] Computed property names not working in template

### ISSUE THREAD

**Issue by mahammad-sixberries** [JuniorTour/vue-template-babel-compiler#28]
- [ ] Would you like to work on a fix?

## Current behavior
``` js
:class="{
    [class1]: condition1,
    [class2]: condition2,
}"
```

## Expected behavior
Computed property names should be working as per [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names)

**Comment by JuniorTour** [comment]
Thanks for you feedback.

It is a Bug.

<hr/>

It has something to do with [@babel/plugin-transform-computed-properties && assumptions.setComputedProperties](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAhhC8EG8DaBjYUDOGCMBdAXBAOREC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.16.6&externalPlugins=%40babel%2Fplugin-transform-computed-properties%407.16.5&assumptions=%7B%22setComputedProperties%22%3Atrue%7D)

We may need prepend `_vm.` to computed class property too:

https://github.com/JuniorTour/vue-template-babel-compiler/blob/main/src/plugins/utils/shouldPrependVM.js#L21-L35

If anyone has interest to fix this issue, follow the [CONTRIBUTING.md](https://github.com/JuniorTour/vue-template-babel-compiler/blob/main/CONTRIBUTING.md) will help you.

**Comment by JuniorTour** [comment]
I have fixed this issue.
You can try it by run:
`npm install vue-template-babel-compiler@latest`

Thanks for your feedback again!
