### ISSUE TITLE
[Bug] Use object spread in template not work

### ISSUE THREAD

**Issue by vip30** [JuniorTour/vue-template-babel-compiler#9]
## Description
Using object spread in template got error
``` js
<template>
  <div class="hello">
   .
   .
   .
   <h3 v-if="{...a}">Installed CLI Plugins</h3>
</template>
```

## Current behavior
Throw error message 
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "ReferenceError: _objectSpread is not defined"

found in

---> <HelloWorld> at src/components/HelloWorld.vue
       <App> at src/App.vue
         <Root>
```

## Expected behavior
Object spread can be used

**Comment by JuniorTour** [comment]
Duplicate https://github.com/JuniorTour/vue-template-babel-compiler/issues/10

**Comment by vip30** [comment]
> Duplicate #10

I think it's not the same issue?

Seems your func getFunctionBody erased the import statement from babel

```
function getFunctionBody(code) {
  const range = getMarkRange(code, '{', '}');
  
  return code.substring(range.start, range.end);
}
```

```
  var _objectSpread = require(".../node_modules/@babel/runtime/helpers/objectSpread2")
    .default
```

**Comment by JuniorTour** [comment]
It is a bug. 
Sorry, my mistake.

@vip30 Your solution is clever, Thank you! :blush:

However, the root reason is this lib NOT compile `object spread`.

I prefer to add [babel-plugin-proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#usebuiltins) to: https://github.com/JuniorTour/vue-template-babel-compiler/blob/96bb88929e9c13cc8d408c5045bb1d984d869f2a/src/renderCompiler.js#L19

And enable its `useBuiltins option`, use `Object.assign` to substitute `_objectSpread` helper func:
``` js
["@babel/plugin-proposal-object-rest-spread", { useBuiltIns: true }]
```
<hr />
Do you have interest to work on a fix?

Here is a [Contribute guide](https://github.com/JuniorTour/vue-template-babel-compiler/blob/main/CONTRIBUTING.md).

Really appreciate your feedback!

**Comment by vip30** [comment]
> It is a bug.
> Sorry, my mistake.
> 
> @vip30 Your solution is clever, Thank you! 😊
> 
> However, the root reason is this lib NOT compile `object spread`.
> 
> I prefer to add [babel-plugin-proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#usebuiltins) to:
> 
> https://github.com/JuniorTour/vue-template-babel-compiler/blob/96bb88929e9c13cc8d408c5045bb1d984d869f2a/src/renderCompiler.js#L19
> 
> And enable its `useBuiltins option`, use `Object.assign` to substitute `_objectSpread` helper func:
> 
> ```js
> ["@babel/plugin-proposal-object-rest-spread", { useBuiltIns: true }]
> ```
> 
> Do you have interest to work on a fix?
> Here is a [Contribute guide](https://github.com/JuniorTour/vue-template-babel-compiler/blob/main/CONTRIBUTING.md).
> 
> Really appreciate your feedback!

Thanks for your information
Sound better for me

Please review the pr
https://github.com/JuniorTour/vue-template-babel-compiler/pull/11
